### DISCUSSION TITLE
Structurizr as a dev container feature

### DISCUSSION THREAD

**Discussion by ThePlenkov** [structurizr/cli#125] [Ideas] [answered]
### Description

Hi! It would be nice if instead of using prebuild containers we could use devcontainer feature (https://containers.dev/features). In this case we can keep using our devcontianer images but with preinstalled CLI.

### Priority

Low

### Resolution

I have no budget, please add this feature for free

**Comment by simonbrowndotje** [comment]
You might be interested in https://github.com/evilpilaf/structurizr-remotecontainer (linked to from https://github.com/structurizr/cli/blob/master/docs/containers.md).

**Comment by ThePlenkov** [comment]
well - indeed - I understand what you mean, but here is the point. The root container may be different . Someones writes java, someone uses Node, we all use different base containers. But feature approach allows us to share features among base containers actually

**Comment by simonbrowndotje** [comment]
Dev containers isn't something that I use, but you're welcome to add support.

**Comment by JP-Dhabolt** [comment, marked as answer]
This is possible today, it just takes some time during initial devcontainer creation.  In your `devcontainer.json` file, simply add:

```json
{
	"features": {
		"ghcr.io/meaningful-ooo/devcontainer-features/homebrew:2": {}
	},
	"postCreateCommand": "brew install structurizr-cli"
}
```

This will install homebrew via the feature, and install the structurizr-cli via homebrew after the container is created.

As a bonus, you can also add `structurizr/lite` in your `docker-compose.yml` and have it serve up the content alongside your normal devcontainer.  Just modify the `data` directory volume mount to wherever you have your workspace files in the repo.

```yaml
version: '3.8'
services:
  app:
    depends_on:
      - lite
    build: 
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    network_mode: service:lite
  lite:
    image: structurizr/lite
    volumes:
      - ../data:/usr/local/structurizr

```
