### ISSUE TITLE
Provide examples for continous integration

### ISSUE THREAD

**Issue by Kaligule** [structurizr/cli#97]
I tried to get structurizr/cli working in an gitlab-ci for quite some time now.
This is the best I could do, and it is not great (because it redoes a lot of the work that you already do in the Dockerfile, but I just couldn't get that one to work):

```yml
structurizr_export:
  image: eclipse-temurin:17.0.5_8-jre-jammy
  stage: generate_views
  before_script:
    - wget https://static.structurizr.com/download/structurizr-cli.zip
    - apt update && apt install unzip
    - unzip structurizr-cli.zip
  script:
    - bash structurizr.sh export --workspace my_workspace_file.dsl --format mermaid
    - ls -la
```

**Comment by Kaligule** [comment]
Got it to work, the trick was to overwrite the entrypoint. This is what I use now:

```yml
generate_views:
  stage: generate_views
  image:
    name: structurizr/cli
    entrypoint: [""]
  script:
    - /usr/local/structurizr-cli/structurizr.sh export --workspace workspace.dsl --format mermaid
    - ls -lah
  artifacts:
    paths:
      - "*.mmd"
    expire_in: 1 day
```
